### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by KETTY2** [OpenNLPLab/HGRN#3]
I'm trying to run lra but error
Traceback (most recent call last):
  File "/home/dsail/HGRN-main/lra/train.py", line 593, in <module>
    main()
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/dsail/HGRN-main/lra/train.py", line 589, in main
    train(config)
  File "/home/dsail/HGRN-main/lra/train.py", line 524, in train
    trainer.fit(model)
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1439, in _call_setup_hook
    self.call_hook("setup", stage=fn)
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1501, in call_hook
    output = model_fx(*args, **kwargs)
  File "/home/dsail/HGRN-main/lra/train.py", line 83, in setup
    self.model = utils.instantiate(registry.model, self.hparams.model)
  File "/home/dsail/HGRN-main/lra/src/utils/config.py", line 99, in instantiate
    return obj()
  File "/home/dsail/HGRN-main/lra/src/models/sequence/model.py", line 260, in __init__
    block = SequenceResidualBlock(
  File "/home/dsail/HGRN-main/lra/src/models/sequence/block.py", line 36, in __init__
    self.layer = utils.instantiate(registry.layer, layer, d_input)
  File "/home/dsail/HGRN-main/lra/src/utils/config.py", line 99, in instantiate
    return obj()
TypeError: __init__() got an unexpected keyword argument 'transposed'

keep happens .......
could you please help?

**Comment by Doraemonzzz** [comment]
Could you provide the version of PyTorch Lightning? My version is 2.0.4.

**Comment by KETTY2** [comment]
Thank you for quick reply! I really appreciate it. mine was 1.5.10. but updating to 2.0.4 I faced torch 1.11.0 which is mentioned in env2 does not fit with 2.0.4.... could you give me more information about version information??

**Comment by KETTY2** [comment]
also updating to torch 2.4.1 which matches with 2.0.4 make bellow error.......
  File "/home/dsail/HGRN-main/lra/train.py", line 18, in <module>
    from src.dataloaders import SequenceDataset  # TODO make registry
  File "/home/dsail/HGRN-main/lra/src/dataloaders/__init__.py", line 1, in <module>
    from .datasets import SequenceDataset
  File "/home/dsail/HGRN-main/lra/src/dataloaders/datasets.py", line 20, in <module>
    import torchtext
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/torchtext/__init__.py", line 5, in <module>
    from . import vocab
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/torchtext/vocab/__init__.py", line 11, in <module>
    from .vocab_factory import (
  File "/home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/torchtext/vocab/vocab_factory.py", line 4, in <module>
    from torchtext._torchtext import (
ImportError: /home/dsail/anaconda3/envs/lra/lib/python3.8/site-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo

**Comment by Doraemonzzz** [comment]
You can try the environment [here](https://github.com/OpenNLPLab/HGRN/blob/main/env2.yaml); the environment for HGRN is somewhat outdated.

**Comment by KETTY2** [comment]
the link you suggests points to same HGRN env2 I used........

**Comment by Doraemonzzz** [comment]
Sorry, I gave the wrong link. The link should actually be [here](https://github.com/OpenNLPLab/HGRN2/blob/main/lra.yaml).

**Comment by KETTY2** [comment]
Thank you so much!! I will try it :)
